/**
 * ============================================================================
 * e107 Admin Dependent Fields & Tabs Helper
 * ============================================================================
 *
 * DESCRIPTION
 * ----------------------------------------------------------------------------
 * Generic dependency handler for e107 Admin UI preferences.
 *
 * This script provides:
 *
 *  - Field-to-field dependencies
 *  - Master switch (global form lock)
 *  - Tab dependencies
 *  - Full compatibility with e107 boolean fields (bootstrap-switch)
 *  - Support for AND / OR logical rules
 *
 * Designed to be reusable across any e107 plugin without modifying core.
 *
 *
 * ============================================================================
 * FIELD DEPENDENCIES
 * ============================================================================
 *
 * Dependencies are defined via writeParms using the attribute:
 *
 *     'data-depends' => 'field_name:value'
 *
 * Example:
 *
 *     'reset_delay' => [
 *         'type' => 'number',
 *         'writeParms' => [
 *             'data-depends' => 'autoreset:1'
 *         ]
 *     ]
 *
 *
 * Supported rule syntax:
 *
 *  Single condition:
 *      autoreset:1
 *
 *  AND condition (comma separated):
 *      autoreset:1,reset_counter:1
 *
 *  OR condition (pipe separated):
 *      autoreset:1|reset_counter:1
 *
 *
 * When a rule evaluates to FALSE:
 *
 *  - The field is disabled
 *  - Its table row (<tr>) receives the class .e-dep-disabled
 *
 *
 * ============================================================================
 * MASTER SWITCH (GLOBAL FORM CONTROL)
 * ============================================================================
 *
 * A single field may be marked as a Master Switch using:
 *
 *     'data-depmaster' => 'true'
 *
 * Example:
 *
 *     'allow_feature' => [
 *         'type' => 'boolean',
 *         'writeParms' => [
 *             'label' => 'yesno',
 *             'data-depmaster' => 'true'
 *         ]
 *     ]
 *
 *
 * Behavior:
 *
 *  When OFF:
 *      - All form fields are disabled
 *      - All rows receive .e-dep-disabled
 *      - Only the master field and submit button remain active
 *      - Dependent tabs are disabled
 *
 *  When ON:
 *      - Normal dependency evaluation resumes
 *
 * Only one master switch per form is recommended.
 *
 *
 * ============================================================================
 * TAB DEPENDENCIES
 * ============================================================================
 *
 * Tab rules are defined in PHP using e107::js('settings'):
 *
 *     e107::js('settings', [
 *         'adminTabDependencies' => [
 *             1 => ['depends' => 'allow_feature:1'],
 *             2 => ['depends' => 'allow_feature:1'],
 *         ]
 *     ]);
 *
 *
 * Rules:
 *
 *  - The array key corresponds to the tab index (#tab-0, #tab-1, etc.)
 *  - Tab 0 is always considered safe and will never be disabled
 *
 *
 * Behavior:
 *
 *  - Invalid tabs are visually disabled
 *  - pointer-events are blocked
 *  - If the active tab becomes invalid, the system switches to Tab 0
 *
 *
 * ============================================================================
 * BOOLEAN / BOOTSTRAP SWITCH SUPPORT
 * ============================================================================
 *
 * e107 boolean fields use bootstrap-switch, which does NOT reflect
 * the actual saved value directly.
 *
 * This script always reads the hidden input generated by e107:
 *
 *     <input type="hidden" name="pref_name" value="0|1">
 *
 * This guarantees:
 *
 *  - Correct state detection
 *  - Real-time updates
 *  - Full Admin UI compatibility
 *
 *
 * ============================================================================
 * EVENT HANDLING
 * ============================================================================
 *
 * The script automatically reacts to:
 *
 *  - switchChange.bootstrapSwitch
 *  - change
 *  - keyup
 *
 * No manual calls are required.
 *
 *
 * ============================================================================
 * REQUIRED CSS (in eadmin.css)
 * ============================================================================
 *
 * Recommended style:
 *
 *     .e-dep-disabled {
 *         opacity: 0.5;
 *         pointer-events: none;
 *         filter: grayscale(1);
 *     }
 *
 *
 * ============================================================================
 * DESIGN GOALS
 * ============================================================================
 *
 *  ✔ Core-safe (no core modifications)
 *  ✔ Plugin-agnostic
 *  ✔ Fully reusable
 *  ✔ Supports complex logical rules
 *  ✔ Works with e107 Admin UI architecture
 *
 * ============================================================================
 * EXAMPLES
 * ============================================================================
 * 
 * Library loading example
 * e107::js('footer', e_PLUGIN.'eadmin/js/dependent_fields.js', array('type' => 'jquery', 'priority' => 100));
 * 
 * CSS loading is needed to style fields
 * e107::css('url', e_PLUGIN.'eadmin/eadmin.css');
 * * 
 * Admin area usage example:
 *         'PrefOne' => [
            'title' => PREF_ONE,
            'type'  => 'boolean',
            'data'  => 'int',
            'tab'   => 0,
            'writeParms' => ['label' => 'yesno']
        ],
        'PrefTwo'      => ['title' => PREF_TWO, 'type'     => 'number', 'data' => 'int', 'tab'   => 0,
    'writeParms' => [
        'data-depends'      => 'PrefOne:1'
    ]
        ]
    ....
 * 
 * Global master handler setup example
 *         'PrefOne'      => ['title' => LANAD_USERFRIENDS_23, 'type'     => 'boolean', 'data' => 'int', 'tab'   => 0, 'writeParms' => [
            'label' => 'yesno', 'data-depmaster' => 'true'
        ]], 
 *
 *
 * Tabs values handling example
 * e107::js('settings', [
    'adminTabDependencies' => [
        1 => ['depends' => 'PrefOne:1'],
        2 => ['depends' => 'PrefOne:1'],
    ]
]);
 * 
 * 
 */

(function ($) {
    /**
     * Obtém valor real do pref
     */
    function getPrefValue(name) {
        var $el = $('[name="' + name + '"]');
        if (!$el.length) return null;

        var $hidden = $el.filter('input[type="hidden"]');
        if ($hidden.length) return String($hidden.val());

        if ($el.is(':checkbox')) {
            return $el.prop('checked') ? '1' : '0';
        }
        return String($el.val());
    }

    /**
     * Avalia regra simples (name:value)
     */
    function evaluateSingleRule(rule) {
        var parts = rule.split(':');
        if (parts.length !== 2) return false;
        return getPrefValue(parts[0].trim()) === parts[1].trim();
    }

    /**
     * Avalia regra completa com AND/OR
     */
    function evaluateRule(rule) {
        if (!rule) return true;
        if (rule.indexOf('|') !== -1) {
            return rule.split('|').some(function (r) { return evaluateRule(r.trim()); });
        }
        if (rule.indexOf(',') !== -1) {
            return rule.split(',').every(function (r) { return evaluateRule(r.trim()); });
        }
        return evaluateSingleRule(rule.trim());
    }

    /**
     * Atualiza todos os dependentes e gere o Master Switch
     */
    function updateAllDependencies() {
        var $masterField = $('[data-depmaster="true"]');
        if (!$masterField.length) {
            processIndividualDependencies();
            return;
        }

        var masterName = $masterField.attr('name');
        var isMasterOn = (getPrefValue(masterName) === '1');

        if (!isMasterOn) {
            // 2. MASTER OFF: Bloqueia tudo EXCETO o master e o submit
            var $allFields = $('form').find('input, select, textarea, button')
                .not('[name="' + masterName + '"]')
                .not('[type="submit"]');

            $allFields.each(function() {
                var $f = $(this);
                // Nunca desativar o Master nem o botão de Save
                $f.prop('disabled', true);
                
                if ($f.is('select') && typeof $f.select2 === 'function') {
                    $f.trigger('change.select2');
                }
                
                if (typeof $.fn.bootstrapSwitch !== 'undefined' && $f.data('bootstrap-switch')) {
                    $f.bootstrapSwitch('disabled', true);
                }
            });

            // Aplica classe de disabled em todas as linhas, EXCETO na linha do Master
            $('form').find('tr').not($masterField.closest('tr')).addClass('e-dep-disabled');
            
            // Importante: Passamos false para desativar tabs, mas a função vai proteger a Tab 0
            applyTabDependencies(false); 
        } else {
            // 3. MASTER ON: Reset e processamento individual
            var $allFields = $('form').find('input, select, textarea, button').not('[type="submit"]');
            
            $allFields.each(function() {
                var $f = $(this);
                $f.prop('disabled', false);
                if (typeof $.fn.bootstrapSwitch !== 'undefined' && $f.data('bootstrap-switch')) {
                    $f.bootstrapSwitch('disabled', false);
                }
            });
            $('form').find('tr').removeClass('e-dep-disabled');

            processIndividualDependencies(masterName);
            applyTabDependencies(true);
        }
    }

    function processIndividualDependencies(masterName) {
        $('[data-depends]').each(function () {
            var $field = $(this);
            // Proteção REDUNDANTE: nunca mexer no master aqui
            if ($field.attr('name') === masterName) return;

            var rule   = $field.data('depends');
            var valid  = evaluateRule(rule);
            var $row   = $field.closest('tr');

            $field.prop('disabled', !valid);
            if ($field.is('select') && typeof $field.select2 === 'function') { $field.trigger('change.select2'); }
            $row.toggleClass('e-dep-disabled', !valid);
        });
    }

    function applyTabDependencies(globalMasterState) {
        var cfgs = window.e107?.settings?.adminTabDependencies;
        if (!cfgs) return;

        $('.nav-tabs a.nav-link').each(function () {
            var $tab = $(this);
            var match = ($tab.attr('href') || '').match(/tab-(\d+)/);
            if (!match) return;

            var index = match[1];
            
            // PROTEÇÃO DA TAB MASTER: Se for a tab 0 (ou onde o master estiver), nunca desativa
            if (index == "0") {
                $tab.removeClass('disabled e-dep-disabled').css({'pointer-events': 'auto', 'opacity': '1'});
                return; 
            }

            if (!cfgs[index]) return;

            var cfg   = cfgs[index];
            var valid = globalMasterState ? evaluateRule(cfg.depends) : false;

            if (cfg.mode === 'hide') {
                $tab.closest('li').toggle(valid);
            } else {
                $tab.toggleClass('disabled e-dep-disabled', !valid)
                    .css({'pointer-events': valid ? 'auto' : 'none', 'opacity': valid ? '1' : '0.5'});
            }

            // Se a tab ativa "morreu", pula para a Tab 0 que é garantida
            if (!valid && ($tab.hasClass('active') || $tab.parent().hasClass('active'))) {
                $('.nav-tabs a[href*="tab-0"]').tab('show');
            }
        });
    }

    /**
     * INIT
     */
    $(document).ready(function () {
        function bootstrap() {
            if (typeof window.e107?.settings !== 'undefined') {
                updateAllDependencies();
            } else {
                setTimeout(bootstrap, 50);
            }
        }
        bootstrap();

        // Listeners universais para inputs e switches do e107
        $(document).on(
            'switchChange.bootstrapSwitch change keyup',
            'input, select, textarea',
            function () {
                updateAllDependencies();
            }
        );
    });

})(jQuery);
